In [1]:
import pickle
import os
import re
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
with open('df_train_leftMerged.pickle','rb') as k:
    df_train = pickle.load(k)

In [3]:
df_train[['id_33','DeviceType','DeviceInfo']]

id_33 DeviceType                          DeviceInfo
0             NaN        NaN                                 NaN
1             NaN        NaN                                 NaN
2             NaN        NaN                                 NaN
3             NaN        NaN                                 NaN
4       2220x1080     mobile       SAMSUNG SM-G892A Build/NRD90M
5             NaN        NaN                                 NaN
6             NaN        NaN                                 NaN
7             NaN        NaN                                 NaN
8        1334x750     mobile                          iOS Device
9             NaN        NaN                                 NaN
10            NaN    desktop                             Windows
11            NaN    desktop                                 NaN
12            NaN        NaN                                 NaN
13            NaN        NaN                                 NaN
14            NaN        NaN                                 NaN
15            NaN        NaN                                 NaN
16       1280x800    desktop                               MacOS
17       1366x768    desktop                             Windows
18            NaN        NaN                                 NaN
19            NaN        NaN                                 NaN
20            NaN        NaN                                 NaN
21            NaN        NaN                                 NaN
22            NaN        NaN                                 NaN
23            NaN        NaN                                 NaN
24            NaN        NaN                                 NaN
25            NaN        NaN                                 NaN
26            NaN        NaN                                 NaN
27            NaN        NaN                                 NaN
28            NaN        NaN                                 NaN
29            NaN        NaN                                 NaN
...           ...        ...                                 ...
590510        NaN        NaN                                 NaN
590511        NaN        NaN                                 NaN
590512        NaN        NaN                                 NaN
590513        NaN        NaN                                 NaN
590514        NaN        NaN                                 NaN
590515        NaN        NaN                                 NaN
590516        NaN        NaN                                 NaN
590517        NaN        NaN                                 NaN
590518        NaN        NaN                                 NaN
590519        NaN        NaN                                 NaN
590520        NaN        NaN                                 NaN
590521        NaN     mobile             F3111 Build/33.3.A.1.97
590522        NaN        NaN                                 NaN
590523        NaN        NaN                                 NaN
590524        NaN        NaN                                 NaN
590525        NaN        NaN                                 NaN
590526    855x480     mobile                 A574BL Build/NMF26F
590527        NaN        NaN                                 NaN
590528        NaN        NaN                                 NaN
590529        NaN     mobile  Moto E (4) Plus Build/NMA26.42-152
590530        NaN        NaN                                 NaN
590531  2560x1600    desktop                               MacOS
590532        NaN        NaN                                 NaN
590533        NaN        NaN                                 NaN
590534        NaN     mobile         RNE-L03 Build/HUAWEIRNE-L03
590535        NaN        NaN                                 NaN
590536        NaN        NaN                                 NaN
590537        NaN        NaN                                 NaN
590538        NaN        NaN                                 NaN
590539        NaN        NaN                   

In [4]:
def preprocessing(line):
    if line is not np.NaN:
        line = str(line).lower()
        line = re.sub(r"[^\w\s]", '_', line)
        line = re.sub(r"\s+", ' ', line)
    return line

In [5]:
df_train['new_device_info'] = df_train['DeviceInfo'].map(preprocessing, na_action='ignore')

In [6]:
df_train[['DeviceInfo','new_device_info']]

DeviceInfo                     new_device_info
0                                      NaN                                 NaN
1                                      NaN                                 NaN
2                                      NaN                                 NaN
3                                      NaN                                 NaN
4            SAMSUNG SM-G892A Build/NRD90M       samsung sm_g892a build_nrd90m
5                                      NaN                                 NaN
6                                      NaN                                 NaN
7                                      NaN                                 NaN
8                               iOS Device                          ios device
9                                      NaN                                 NaN
10                                 Windows                             windows
11                                     NaN                                 NaN
12                                     NaN                                 NaN
13                                     NaN                                 NaN
14                                     NaN                                 NaN
15                                     NaN                                 NaN
16                                   MacOS                               macos
17                                 Windows                             windows
18                                     NaN                                 NaN
19                                     NaN                                 NaN
20                                     NaN                                 NaN
21                                     NaN                                 NaN
22                                     NaN                                 NaN
23                                     NaN                                 NaN
24                                     NaN                                 NaN
25                                     NaN                                 NaN
26                                     NaN                                 NaN
27                                     NaN                                 NaN
28                                     NaN                                 NaN
29                                     NaN                                 NaN
...                                    ...                                 ...
590510                                 NaN                                 NaN
590511                                 NaN                                 NaN
590512                                 NaN                                 NaN
590513                                 NaN                                 NaN
590514                                 NaN                                 NaN
590515                                 NaN                                 NaN
590516                                 NaN                                 NaN
590517                                 NaN                                 NaN
590518                                 NaN                                 NaN
590519                                 NaN                                 NaN
590520                                 NaN                                 NaN
590521             F3111 Build/33.3.A.1.97             f3111 build_33_3_a_1_97
590522                                 NaN                                 NaN
590523                                 NaN                                 NaN
590524                                 NaN                                 NaN
590525                                 NaN                                 NaN
590526                 A574BL Build/NMF26F                 a574bl build_nmf26f
590527                                 NaN                                 NaN
590528                                 NaN                                 NaN
590

In [8]:
df_train['DeviceInfo'].head

<bound method NDFrame.head of 0                                        NaN
1                                        NaN
2                                        NaN
3                                        NaN
4              SAMSUNG SM-G892A Build/NRD90M
5                                        NaN
6                                        NaN
7                                        NaN
8                                 iOS Device
9                                        NaN
10                                   Windows
11                                       NaN
12                                       NaN
13                                       NaN
14                                       NaN
15                                       NaN
16                                     MacOS
17                                   Windows
18                                       NaN
19                                       NaN
20                                       NaN
21                       

In [10]:
v = TfidfVectorizer()
x = v.fit_transform(df_train['new_device_info'].dropna())

In [16]:
x.toarray()[0].shape

(1615,)

In [18]:
x.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

## Tinkering with TF-IDF and Clustering.

In [66]:
rarray = np.random.randint(2,size=(5000,5))

In [67]:
from sklearn.cluster import KMeans, DBSCAN

In [68]:
kmeans = KMeans(n_clusters=10).fit(rarray)

In [69]:
type(kmeans)

sklearn.cluster.k_means_.KMeans

In [70]:
nrarray = np.random.randint(2,size=(10,5))
print(nrarray)
device_code = kmeans.predict(nrarray)

[[0 0 0 1 0]
 [0 0 1 1 1]
 [0 0 1 1 0]
 [0 0 1 1 1]
 [0 0 0 1 1]
 [0 0 0 0 1]
 [0 1 1 0 0]
 [1 1 0 0 0]
 [1 0 1 1 1]
 [1 1 1 0 0]]


In [71]:
device_code

array([9, 8, 9, 8, 8, 1, 0, 0, 2, 7])

In [85]:
db = DBSCAN(eps=0.3, min_samples=100).fit(rarray)

In [86]:
n_clusters = len(set(db.labels_))
print('Estimated number of clusters: %d' % n_clusters)

Estimated number of clusters: 32


In [87]:
type(db)

sklearn.cluster.dbscan_.DBSCAN

In [88]:
db.fit_predict(nrarray)

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1], dtype=int64)

In [89]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(rarray)

In [90]:
kmeans = KMeans(n_clusters=10).fit(X_scaled)

In [91]:
kmeans.predict(nrarray)

array([0, 0, 0, 0, 9, 5, 8, 2, 9, 2])

In [92]:
nrarray

array([[0, 0, 0, 1, 0],
       [0, 0, 1, 1, 1],
       [0, 0, 1, 1, 0],
       [0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1],
       [0, 1, 1, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 0, 1, 1, 1],
       [1, 1, 1, 0, 0]])

In [93]:
X_scaled

array([[ 1.01409939,  0.98767594, -1.01126343,  1.01126343,  1.00561577],
       [-0.98609664, -1.01247784, -1.01126343, -0.98886202, -0.99441559],
       [-0.98609664, -1.01247784,  0.98886202,  1.01126343, -0.99441559],
       ...,
       [ 1.01409939,  0.98767594, -1.01126343, -0.98886202, -0.99441559],
       [-0.98609664, -1.01247784, -1.01126343,  1.01126343,  1.00561577],
       [-0.98609664,  0.98767594,  0.98886202,  1.01126343, -0.99441559]])